import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import './globals.css';
import TransportBar from "@/components/TransportBar";
import MixerSection from "@/components/Mixer";
import GlobalSection from "@/components/Global";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} font-mono antialiased select-none`}
      >
        <main className="bg-black text-white min-h-screen p-4 flex flex-col">
        <div className="flex flex-col gap-4 md:grid md:grid-cols-12 md:gap-4 flex-grow">
            <div className="md:col-span-6">
              <MixerSection />
            </div>
            {/* <HeaderStrip className="col-span-3" /> */}
            <div className="md:col-span-3" >
              <GlobalSection />
            </div>
          </div>
          <TransportBar  />
          {children}
        </main>
      </body>
    </html>
  );
};
