name: lint-and-format

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: install
        run: npm install
      - name: lint
        run: npm run lint
      - name: prettier
        run: npx prettier . --write
